version: "3"
services:
  acj-db:
    build: ./mongodb
    env_file: ./mongodb/.env
    volumes: 
      - acj-db-data:/data/db
  acj-backend:
    build: ./server
    env_file: ./server/.env
    ports:
      #Bind ports for REST-API
      - "3000:3000"
    volumes:
      #Bind a volume for your certificates
      - /etc/letsencrypt/archive/yourdomain:/project/certs
    depends_on: 
      - acj-db
  acj-frontend:
    build: ./client
    ports:
      #Bind ports for frontend
      - "443:5000"
    depends_on: 
      - acj-db
      - acj-backend
    volumes:
      #Bind a volume for your certificates
      - /etc/letsencrypt/archive/yourdomain:/project/certs
  acj-analyse:
    build: ./AnalyseModule
volumes:
  acj-db-data:
    driver: local
